### ISSUE TITLE
Message to user after receiving BAD-RQST-HDR and BAD-RQST-BODY

### ISSUE THREAD

**Issue by baikauskaite** [baikauskaite/chat-client#14]
Since we're in control with what is happening in our application, these kind of server messages might probably only appear in case there is an error in the channel.

We should probably print to the user something like: `There was a problem. Please resubmit your command.`, so the user would just repeat their input or do something else. We're not really in control of this and we shouldn't handle this either, I think.

**Comment by paigecache** [comment]
Good point; going to create a PR with those changes shortly!
